export const WEATHER_EFFECT_CATEGORIES = [
  { id: 'atmosphere', label: 'Atmosphere' },
  { id: 'nature', label: 'Nature' },
  { id: 'places', label: 'Places' },
  { id: 'artistic', label: 'Artistic' },
  { id: 'digital', label: 'Digital' },
  { id: 'celebration', label: 'Celebration' },
];

export const WEATHER_ART_DIRECTIONS = [
  { id: 'calm', label: 'Calm' },
  { id: 'cinematic', label: 'Cinematic' },
  { id: 'gallery', label: 'Gallery' },
  { id: 'stage', label: 'Stage' },
];

const WEATHER_EFFECT_ART_DIRECTION_BY_ID = {
  none: 'calm',
  rain: 'cinematic',
  cloudy: 'calm',
  sunny: 'gallery',
  mist: 'calm',
  'nordic-frost': 'calm',
  'rain-glass': 'cinematic',
  'underwater-caustics': 'calm',
  'dust-motes': 'calm',
  winter: 'calm',
  autumn: 'gallery',
  spring: 'gallery',
  sakura: 'gallery',
  fireflies: 'calm',
  butterflies: 'gallery',
  lanterns: 'stage',
  aurora: 'calm',
  starfield: 'cinematic',
  desert: 'cinematic',
  tropical: 'stage',
  'desert-mirage': 'cinematic',
  'alpine-cabin': 'cinematic',
  'temple-garden': 'calm',
  coffee: 'cinematic',
  fireplace: 'cinematic',
  'ember-drift': 'cinematic',
  'shoji-dusk': 'gallery',
  'monsoon-veranda': 'cinematic',
  'mediterranean-courtyard': 'gallery',
  'lantern-bazaar': 'stage',
  'tropical-night-market': 'stage',
  'starry-swirl': 'gallery',
  'watercolor-bloom': 'gallery',
  'surreal-dream': 'gallery',
  'ink-wash': 'gallery',
  'prism-stage': 'stage',
  'stained-glass': 'gallery',
  'monochrome-film': 'cinematic',
  'brutalist-light': 'stage',
  matrix: 'stage',
  'neon-grid': 'stage',
  'festival-confetti': 'stage',
};

const WEATHER_EFFECT_DEFINITIONS = [
  {
    id: 'none',
    name: 'None',
    icon: '🚫',
    description: 'Keep the background clean and still.',
    category: 'atmosphere',
    renderer: 'none',
    defaultConfig: { color: '#FFFFFF', opacity: 0, velocity: 1 },
  },
  {
    id: 'rain',
    name: 'Rain',
    icon: '🌧️',
    description: 'Fine cinematic rainfall with layered depth.',
    category: 'atmosphere',
    renderer: 'canvas',
    defaultConfig: { color: '#4682B4', opacity: 0.64, velocity: 0.94 },
  },
  {
    id: 'cloudy',
    name: 'Cloudy',
    icon: '☁️',
    description: 'Soft atmospheric cloud cover and haze.',
    category: 'atmosphere',
    renderer: 'dom',
    defaultConfig: { color: '#FFFFFF', opacity: 0.8, velocity: 1 },
  },
  {
    id: 'sunny',
    name: 'Sunny',
    icon: '☀️',
    description: 'Warm golden light with drifting flares.',
    category: 'atmosphere',
    renderer: 'dom',
    defaultConfig: { color: '#FFD700', opacity: 0.2, velocity: 1 },
  },
  {
    id: 'mist',
    name: 'Mist',
    icon: '🌫️',
    description: 'Layered fog banks with slow cinematic drift.',
    category: 'atmosphere',
    renderer: 'canvas',
    defaultConfig: { color: '#D8E3EA', opacity: 0.56, velocity: 0.78 },
  },
  {
    id: 'nordic-frost',
    name: 'Nordic Frost',
    icon: '🧊',
    description: 'Frosted edges, pale haze, and crisp winter light.',
    category: 'atmosphere',
    renderer: 'dom',
    defaultConfig: { color: '#D7EEFF', opacity: 0.64, velocity: 0.82 },
  },
  {
    id: 'rain-glass',
    name: 'Rain on Glass',
    icon: '🪟',
    description: 'Window droplets sliding through a dark rainy glow.',
    category: 'atmosphere',
    renderer: 'canvas',
    defaultConfig: { color: '#8FC3FF', opacity: 0.64, velocity: 0.88 },
  },
  {
    id: 'underwater-caustics',
    name: 'Underwater Caustics',
    icon: '🌊',
    description: 'Soft teal light ripples with submerged depth.',
    category: 'atmosphere',
    renderer: 'dom',
    defaultConfig: { color: '#69D5FF', opacity: 0.62, velocity: 0.8 },
  },
  {
    id: 'dust-motes',
    name: 'Dust Motes',
    icon: '✨',
    description: 'Sunlit dust floating gently through warm air.',
    category: 'atmosphere',
    renderer: 'canvas',
    defaultConfig: { color: '#F5D9A8', opacity: 0.46, velocity: 0.74 },
  },
  {
    id: 'winter',
    name: 'Winter',
    icon: '❄️',
    description: 'Layered snowfall with soft bloom.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#FFFFFF', opacity: 0.6, velocity: 1 },
  },
  {
    id: 'autumn',
    name: 'Autumn',
    icon: '🍂',
    description: 'Tumbling leaves with warm, dry motion.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#D2691E', opacity: 0.7, velocity: 1 },
  },
  {
    id: 'spring',
    name: 'Spring',
    icon: '🌸',
    description: 'Fresh blooms drifting through the air.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#FFB6C1', opacity: 0.7, velocity: 1 },
  },
  {
    id: 'sakura',
    name: 'Cherry Blossoms',
    icon: '🌸',
    description: 'Delicate petals with elegant spirals.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#FFB7C5', opacity: 0.8, velocity: 1 },
  },
  {
    id: 'fireflies',
    name: 'Fireflies',
    icon: '✨',
    description: 'Glowing dots with a slow summer pulse.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#FFD700', opacity: 0.9, velocity: 1 },
  },
  {
    id: 'butterflies',
    name: 'Butterflies',
    icon: '🦋',
    description: 'Fluttering silhouettes with organic arcs.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#FF69B4', opacity: 0.85, velocity: 1 },
  },
  {
    id: 'lanterns',
    name: 'Lanterns',
    icon: '🏮',
    description: 'Floating lanterns with a warm dusk glow.',
    category: 'places',
    renderer: 'canvas',
    defaultConfig: { color: '#FF0000', opacity: 0.85, velocity: 1 },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    icon: '🌌',
    description: 'Diffuse northern lights sweeping overhead.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#00FF80', opacity: 0.6, velocity: 1 },
  },
  {
    id: 'starfield',
    name: 'Starfield',
    icon: '🌠',
    description: 'Deep-space drift with twinkling comets.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#8AB4FF', opacity: 0.78, velocity: 1 },
  },
  {
    id: 'desert',
    name: 'Desert',
    icon: '🏜️',
    description: 'Dry sand drift in low-contrast layers.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#DEB887', opacity: 0.5, velocity: 1 },
  },
  {
    id: 'tropical',
    name: 'Tropical',
    icon: '🌴',
    description: 'Vibrant petals and warm island motion.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#FF69B4', opacity: 0.8, velocity: 1 },
  },
  {
    id: 'desert-mirage',
    name: 'Desert Mirage',
    icon: '🏜️',
    description: 'Heat shimmer, bright horizon bloom, and distant haze.',
    category: 'nature',
    renderer: 'dom',
    defaultConfig: { color: '#F1C27D', opacity: 0.66, velocity: 0.82 },
  },
  {
    id: 'alpine-cabin',
    name: 'Alpine Cabin',
    icon: '🏔️',
    description: 'Cold snowfall outside with warm ember lift below.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#B9D9FF', opacity: 0.68, velocity: 0.88 },
  },
  {
    id: 'temple-garden',
    name: 'Temple Garden',
    icon: '🌿',
    description: 'Calm green drift with petals and firefly glints.',
    category: 'nature',
    renderer: 'canvas',
    defaultConfig: { color: '#8FD8A7', opacity: 0.62, velocity: 0.78 },
  },
  {
    id: 'coffee',
    name: 'Coffee Shop',
    icon: '☕',
    description: 'Soft smoke columns and ambient warmth.',
    category: 'places',
    renderer: 'canvas',
    defaultConfig: { color: '#8B4513', opacity: 0.6, velocity: 1 },
  },
  {
    id: 'fireplace',
    name: 'Fireplace',
    icon: '🔥',
    description: 'Ember-rich flame glow with subtle flicker.',
    category: 'places',
    renderer: 'canvas',
    defaultConfig: { color: '#FF4500', opacity: 0.8, velocity: 1 },
  },
  {
    id: 'ember-drift',
    name: 'Ember Drift',
    icon: '🔥',
    description: 'Slow rising sparks against a deep evening glow.',
    category: 'places',
    renderer: 'canvas',
    defaultConfig: { color: '#FF8A3D', opacity: 0.68, velocity: 0.82 },
  },
  {
    id: 'shoji-dusk',
    name: 'Shoji Dusk',
    icon: '🪟',
    description: 'Warm paper light, shadow bars, and quiet dusk dust.',
    category: 'places',
    renderer: 'dom',
    defaultConfig: { color: '#F7C986', opacity: 0.72, velocity: 0.84 },
  },
  {
    id: 'monsoon-veranda',
    name: 'Monsoon Veranda',
    icon: '⛈️',
    description: 'Dense rain sheets with humid amber shelter light.',
    category: 'places',
    renderer: 'canvas',
    defaultConfig: { color: '#7CB8FF', opacity: 0.68, velocity: 0.92 },
  },
  {
    id: 'mediterranean-courtyard',
    name: 'Mediterranean Courtyard',
    icon: '🏛️',
    description: 'Bright limewash light, warm stone glow, and dry air.',
    category: 'places',
    renderer: 'dom',
    defaultConfig: { color: '#FFD38A', opacity: 0.64, velocity: 0.84 },
  },
  {
    id: 'lantern-bazaar',
    name: 'Lantern Bazaar',
    icon: '🏮',
    description: 'Golden lantern halos and patterned night shadows.',
    category: 'places',
    renderer: 'dom',
    defaultConfig: { color: '#FFB347', opacity: 0.72, velocity: 0.88 },
  },
  {
    id: 'tropical-night-market',
    name: 'Tropical Night Market',
    icon: '🌺',
    description: 'Humid neon haze with warm lantern color pops.',
    category: 'places',
    renderer: 'dom',
    defaultConfig: { color: '#FF7CB6', opacity: 0.74, velocity: 0.9 },
  },
  {
    id: 'starry-swirl',
    name: 'Starry Swirl',
    icon: '🌀',
    description: 'Painterly night spirals with luminous drifting stars.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#7FA7FF', opacity: 0.74, velocity: 0.82 },
  },
  {
    id: 'watercolor-bloom',
    name: 'Watercolor Bloom',
    icon: '🎨',
    description: 'Soft pigment clouds and paper-wash edges in motion.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#F39AC5', opacity: 0.66, velocity: 0.78 },
  },
  {
    id: 'surreal-dream',
    name: 'Surreal Dream',
    icon: '🌙',
    description: 'An eclipsed horizon with impossible shapes and warm dusk glow.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#FFCB77', opacity: 0.72, velocity: 0.82 },
  },
  {
    id: 'ink-wash',
    name: 'Ink Wash',
    icon: '🖌️',
    description: 'Monochrome brush plumes with paper grain and quiet contrast.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#D6DEE7', opacity: 0.6, velocity: 0.72 },
  },
  {
    id: 'prism-stage',
    name: 'Prism Stage',
    icon: '🎬',
    description: 'Music-video light beams, lens haze, and refracted color planes.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#8D7CFF', opacity: 0.8, velocity: 0.94 },
  },
  {
    id: 'stained-glass',
    name: 'Stained Glass',
    icon: '🪟',
    description: 'Luminous panes, leaded geometry, and cathedral-like color bloom.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#F6B73C', opacity: 0.72, velocity: 0.76 },
  },
  {
    id: 'monochrome-film',
    name: 'Monochrome Film',
    icon: '🎞️',
    description: 'Film-grain atmosphere with projector flicker and silver-halide glow.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#F3F0E8', opacity: 0.62, velocity: 0.86 },
  },
  {
    id: 'brutalist-light',
    name: 'Brutalist Light',
    icon: '🧱',
    description: 'Hard-edged architecture, concrete planes, and stage-like light cuts.',
    category: 'artistic',
    renderer: 'dom',
    defaultConfig: { color: '#E9DED0', opacity: 0.7, velocity: 0.88 },
  },
  {
    id: 'matrix',
    name: 'Matrix',
    icon: '💻',
    description: 'Neon code rain with digital afterglow.',
    category: 'digital',
    renderer: 'canvas',
    defaultConfig: { color: '#00FF41', opacity: 0.82, velocity: 1 },
  },
  {
    id: 'neon-grid',
    name: 'Neon Grid',
    icon: '🌐',
    description: 'Retro-futurist scanlines and glowing perspective grid.',
    category: 'digital',
    renderer: 'dom',
    defaultConfig: { color: '#35F0FF', opacity: 0.74, velocity: 0.92 },
  },
  {
    id: 'festival-confetti',
    name: 'Festival Confetti',
    icon: '🎉',
    description: 'Colorful celebratory pieces with playful wobble.',
    category: 'celebration',
    renderer: 'canvas',
    defaultConfig: { color: '#FF5F5F', opacity: 0.78, velocity: 0.94 },
  },
];

export const WEATHER_EFFECTS = WEATHER_EFFECT_DEFINITIONS.map((effect) => ({
  ...effect,
  artDirection: WEATHER_EFFECT_ART_DIRECTION_BY_ID[effect.id] || 'calm',
}));

const WEATHER_ART_DIRECTION_MAP = WEATHER_ART_DIRECTIONS.reduce((directionMap, direction) => {
  directionMap[direction.id] = direction;
  return directionMap;
}, {});

export const WEATHER_EFFECT_OPTIONS = WEATHER_EFFECTS.map(({ defaultConfig, ...effect }) => effect);

export const WEATHER_EFFECT_MAP = WEATHER_EFFECTS.reduce((effectMap, effect) => {
  effectMap[effect.id] = effect;
  return effectMap;
}, {});

export const DEFAULT_WEATHER_CONFIG = WEATHER_EFFECTS.reduce((config, effect) => {
  config[effect.id] = effect.defaultConfig;
  return config;
}, {});

export const getWeatherEffectsByCategory = () => {
  return WEATHER_EFFECT_CATEGORIES.map((category) => ({
    ...category,
    effects: WEATHER_EFFECT_OPTIONS.filter((effect) => effect.category === category.id),
  })).filter((category) => category.effects.length > 0);
};

export const getWeatherEffectsByArtDirection = () => {
  return WEATHER_ART_DIRECTIONS.map((artDirection) => ({
    ...artDirection,
    effects: WEATHER_EFFECT_OPTIONS.filter((effect) => effect.artDirection === artDirection.id),
  })).filter((artDirection) => artDirection.effects.length > 0);
};

export const getWeatherArtDirection = (artDirectionId) => WEATHER_ART_DIRECTION_MAP[artDirectionId] || WEATHER_ART_DIRECTION_MAP.calm;

export const getWeatherArtDirectionLabel = (artDirectionId) => getWeatherArtDirection(artDirectionId).label;

export const getWeatherEffect = (effectId) => WEATHER_EFFECT_MAP[effectId] || WEATHER_EFFECT_MAP.none;

export const getWeatherEffectLabel = (effectId) => getWeatherEffect(effectId).name;